const download = require('./tasks/download')
const build = require('./tasks/build')
const pdf = require('./tasks/pdf')
const screenshot = require('./tasks/screenshot')
const open = require('./tasks/open')
